### ISSUE TITLE
Some posts not displaying correctly

### ISSUE THREAD

**Issue by koffisani** [tinypressco/tinypress#5]
Some of my post are not using my style and display in plain text. Can somebody look and tell me whether I'm doing wrong stuff ?
My blog is at https://koffisani.github.io/ and the recent [article](https://koffisani.github.io/2016/11/29/2016-11-29-overleaf-l-outil-d-dition-en-ligne-des-documents-scientifiques.html) doesn't even have the title I provided.
Thanks.

**Comment by adamhathcock** [comment]
I'm having publish issues as well.  The latest post shows on the index but no page is made.

https://adamhathcock.github.io

**Comment by adamhathcock** [comment]
Turns out my problem was because I had some invalid character in my title.  I guess it was `!` or `:`

**Comment by koffisani** [comment]
Ah, for sure. Some characters make it impossible to build the site. It's also my problem, I fix it.
